cov-mockbuild: implement proper locking of mock profiles

diff --git a/cov-mockbuild b/cov-mockbuild
--- a/cov-mockbuild
+++ b/cov-mockbuild
@@ -294,6 +294,7 @@ cmd_wrap() {
 
 # profile-level lock file
 LOCK="/tmp/.cov-mockbuild-${MOCK_PROFILE}.lock"
+MLOCK="/tmp/.cov-mockbuild-${MOCK_PROFILE}.metalock"
 
 # prepare $TMP directory
 TMP="`mktemp -d $TMPDIR/cov-mockbuild.XXXXXX`"
@@ -302,7 +303,7 @@ mkdir -p "$BASE_DIR" || die "mktemp failed"
 
 # from now on, do the pack/cleanup on exit, no matter if we succeeded or not
 trap "test -z \"\$EC\" || touch \"${BASE_DIR}.FAILED\"
-    test $$ = \"\$(<$LOCK)\" && rm -fv '$LOCK'
+    test -r \"$LOCK\" && test $$ = \"\$(<$LOCK)\" && rm -fv '$LOCK'
     cmd_wrap tar $TAR_OPTS -cvf '$TGZ' -C '$TMP' '$BASE'
     echo --- $SELF: removing $TMP... 2>&1; rm -rf '$TMP'" EXIT
 
@@ -471,13 +472,15 @@ mock_wrap(){
         | tee --append "$LOG"
 }
 
-# FIXME: use a safe locking algorithm instead
-while test -f "$LOCK"; do
-    printf ">>> %s\twaiting till %s (PID %s) disappears...\n" "`date`" "$LOCK" \
-        "$(<$LOCK)"
-    sleep 15
-done
-echo $$ > "$LOCK" || die "failed to create lock file"
+# acquire the profile-level lock
+flock -w15 "$MLOCK" -c \
+    "while test -f '$LOCK'; do
+        printf '>>> %s\twaiting till %s (PID %s) disappears...\n' \
+            \"\`date\`\" '$LOCK' \"\$(<$LOCK)\"
+        sleep 15
+    done
+    echo $$ > '$LOCK'"
+test $$ = "$(<$LOCK)" || die "failed to create lock file"
 
 # initialize mock chroot
 mock_wrap --init \
