csmock: allow to pass over custom arguments to cov-analyze

diff --git a/cov-diffbuild b/cov-diffbuild
--- a/cov-diffbuild
+++ b/cov-diffbuild
@@ -8,7 +8,7 @@ test -z "$TMPDIR" && TMPDIR="/tmp"
 OPTS="fi"
 
 usage(){
-    echo "Usage: $SELF [-$OPTS] MOCK_PROFILE my-package.src.rpm"
+    echo "Usage: $SELF [-$OPTS] MOCK_PROFILE my-package.src.rpm [COV_OPTS]"
     exit 1
 }
 
@@ -48,6 +48,11 @@ test -n "$SRPM" || usage
 test -r "$SRPM" || die "failed to open $SRPM"
 rpm -pq "$SRPM" || die "failed to open an RPM package: $SRPM"
 
+# look for cov-mockbuild
+TOP="`dirname "$SELF"`"
+COV_MOCKBUILD="`readlink -f "$TOP/cov-mockbuild"`"
+test -x "$COV_MOCKBUILD" || die "cov-mockbuild not found"
+
 BASE="`basename "$SRPM" .src.rpm`"
 COV="$BASE.cov"
 LOG="$BASE.log"
@@ -61,10 +66,10 @@ fi
 
 test -e "$TGZ" && die "'$TGZ' already exists"
 
-# look for cov-mockbuild
-TOP="`dirname "$SELF"`"
-COV_MOCKBUILD="`readlink -f "$TOP/cov-mockbuild"`"
-test -x "$COV_MOCKBUILD" || die "cov-mockbuild not found"
+# extra options for cov-analyze
+shift
+shift
+COV_OPTS="$*"
 
 # create the directory for results in $TMPDIR
 TMP="`mktemp -d $TMPDIR/cov-diffbuild.XXXXXX`"
@@ -95,7 +100,7 @@ write_logs_to(){
 }
 
 cmd_wrap() {
-    printf "\n>>> %s %s\n" "`date`" "$*" >&2
+    printf "\n>>> %s\t%s\n" "`date`" "$*" >&2
     "$@" < /dev/null
     last_ec=$?
 
@@ -107,14 +112,16 @@ cmd_wrap() {
     return $last_ec
 }
 
-pushd "$RESULTS_DIR" || die
+pushd "$RESULTS_DIR" >/dev/null || die
 
 # build the package without patches
-cmd_wrap "$COV_MOCKBUILD" -x $MOCK_PROFILE "$SRPM" || touch run0.FAILED
+cmd_wrap "$COV_MOCKBUILD" -x $MOCK_PROFILE "$SRPM" $COV_OPTS \
+    || touch run0.FAILED
 write_logs_to "run0" 2>/dev/null
 
 # build the package with patches
-cmd_wrap "$COV_MOCKBUILD" $MOCK_PROFILE "$SRPM" || touch run1.FAILED
+cmd_wrap "$COV_MOCKBUILD" $MOCK_PROFILE "$SRPM" $COV_OPTS \
+    || touch run1.FAILED
 write_logs_to "run1" 2>/dev/null
 
 # compare both defect lists
@@ -123,5 +130,5 @@ cmd_wrap csdiff "run0/$ERR" "run1/$ERR"     \
     || touch ./diff.FAILED
 
 # finally write the results
-popd
+popd >/dev/null || die
 cmd_wrap tar -cv -C "$TMP" "$BASE" | lzma -c > "$TGZ"
