cov-mockbuild: create run?.FAILED on its own
As long as cov-mockbuild can run separately, we cannot rely on
cov-diffbuild anymore for handling errors.

diff --git a/cov-mockbuild b/cov-mockbuild
--- a/cov-mockbuild
+++ b/cov-mockbuild
@@ -12,6 +12,7 @@ test -z "$TMPDIR" && TMPDIR="/tmp"
 RPMM="\
 --define '_smp_mflags -ij5' \
 --define '_without_testsuite 1' \
+--define 'libguestfs_runtests 0' \
 --define 'runselftest 0' \
 --define 'with_docs 0' \
 --define 'with_publican 0'"
@@ -77,12 +78,25 @@ MOCK_PROFILE="$1"
 MOCK_CFG="/etc/mock/$MOCK_PROFILE.cfg"
 test -f "$MOCK_CFG" || usage
 
+EC=
+update_ec() {
+    last_ec=$?
+    if test 128 -le "$last_ec" -a "$last_ec" -lt 192; then
+        echo "<<< $SELF: child signalled to die by $(($last_ec - 128))" >&2
+        exit $last_ec
+    fi
+
+    echo "--- $SELF: exit code was: $last_ec" >&2
+    test -n "$EC" || EC=$last_ec
+}
+
 die(){
     if test -n "$1"; then
         echo "$SELF: error: $1" >&2
     else
         echo "$SELF: generic error" >&2
     fi
+    update_ec 1
     exit 1
 }
 
@@ -119,25 +133,14 @@ cmd_wrap() {
     "$@"
 }
 
-EC=
-update_ec() {
-    last_ec=$?
-    if test 128 -le "$last_ec" -a "$last_ec" -lt 192; then
-        echo "<<< $SELF: child signalled to die by $(($last_ec - 128))" >&2
-        exit $last_ec
-    fi
-
-    echo "--- $SELF: exit code was: $last_ec" >&2
-    test -n "$EC" || EC=$last_ec
-}
-
 # prepare $TMP directory
 TMP="`mktemp -d $TMPDIR/cov-mockbuild.XXXXXX`"
 BASE_DIR="$TMP/$BASE/$RUN"
 mkdir -p "$BASE_DIR" || die "mktemp failed"
 
 # from now on, do the pack/cleanup on exit, no matter if we succeeded or not
-trap "cmd_wrap tar $TAR_OPTS -cvf '$TGZ' -C '$TMP' '$BASE'
+trap "test -z \"\$EC\" || touch \"${BASE_DIR}.FAILED\"
+    cmd_wrap tar $TAR_OPTS -cvf '$TGZ' -C '$TMP' '$BASE'
     echo --- $SELF: removing $TMP... 2>&1; rm -rf '$TMP'" EXIT
 
 INI="$BASE_DIR/$BASE.ini"
@@ -374,7 +377,7 @@ mock_wrap --copyin "$TPL" /tmp  || die "mock --copyin failed"
 rm -f "$TPL"
 
 # prepare all we need to build the package
-mock_wrap --chroot "tar -C / -xvf \"/tmp/$TPL_BASE\"" || die "bootstrap failed"
+mock_wrap --chroot "tar -C / -xf \"/tmp/$TPL_BASE\"" || die "bootstrap failed"
 mock_wrap --install "xml-common" "yum-utils" || die "mock --install failed"
 
 SPEC="`rpm -lpq "$SRPM_DUP" 2>/dev/null | grep '\.spec$'`"
